export const featuredListings = [
  {
    title: 'Bakır Mahallesi’nde kaçırılmayacak fırsat',
    category: 'Konut',
    location: 'Kırkağaç, Bakır Mahallesi',
    price: '5.100.000 TL',
    image: 'https://cdn.satariz.com/uploads/image-f71cb722-f01b-4a0a-a1de-8f654fe0e8dc-medium.webp',
    detailUrl: 'https://www.satariz.com/ilan/emlak-konut-satilik-dehir-emlaktan-bakir-mahallesinde-kacirilmayacak-firsat-1000089248',
  },
  {
    title: 'Müstakil tadında konut ve depolu',
    category: 'Konut',
    location: 'Kırkağaç, Manisa',
    price: '5.500.000 TL',
    image: 'https://cdn.satariz.com/uploads/image-2d19c68b-165d-4632-938c-418cc6f670e6-medium.webp',
    detailUrl: 'https://www.satariz.com/ilan/emlak-konut-satilik-dehir-emlaktan-mustakil-tadinda-konut-ve-depolu-1000089244',
  },
  {
    title: 'Satılık konut fırsatı',
    category: 'Konut',
    location: 'Kırkağaç, Manisa',
    price: 'İlanı inceleyin',
    image: 'https://cdn.satariz.com/uploads/image-ad648ecc-4e63-4e34-84e9-633e98f04b78-medium.webp',
    detailUrl: 'https://www.satariz.com/ilan/emlak-konut-satilik-dehir-emlaktan-satilik-1000089240',
  },
  {
    title: 'Şehir merkezinde 420 m² depo',
    category: 'İş Yeri',
    location: 'Kırkağaç Merkez',
    price: '4.750.000 TL',
    image: 'https://cdn.satariz.com/uploads/image-ce01b94f-a90b-4aba-8bb8-58988444b204-medium.webp',
    detailUrl: 'https://www.satariz.com/ilan/emlak-konut-satilik-sehir-merkezinde-420-m2-depo-1000089243',
  },
  {
    title: '30 yaşında tirilya bahçesi',
    category: 'Zeytinlik',
    location: 'Kırkağaç, Manisa',
    price: 'İlanı inceleyin',
    image: 'https://cdn.satariz.com/uploads/image-1adf8d1d-3ada-464b-bb2e-4b2d1c93ba63-medium.webp',
    detailUrl: 'https://www.satariz.com/ilan/emlak-toprak-arsa-acil-dehir-emlaktan-30-yasinda-tirilya-bahcesi-1000089241',
  },
  {
    title: 'Bakımlı satılık zeytinlik',
    category: 'Zeytinlik',
    location: 'Kırkağaç, Manisa',
    price: '1.350.000 TL',
    image: 'https://cdn.satariz.com/uploads/image-4790ce01-32dc-496f-b444-54762425f8b4-medium.webp',
    detailUrl: 'https://www.satariz.com/ilan/emlak-toprak-arsa-dehir-emlaktan-aciilll-satilik-bakimli-zeytinlik-1000089242',
  },
]
